name: readable
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/FlutterQueen/readable

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  lint: ^1.7.2
  test: ^1.20.0
